### ISSUE TITLE
Can we get Android support

### ISSUE THREAD

**Issue by rajubhusani** [sikandaramla/UAEPassOAuthCodeLibrary#1]
Hi,

Can I get the UAE Pass OAuth implemented for Android? Or any suggestions on this? How this was implemented and on what basis you gone through this? Can I get some pointers on this.

**Comment by sikandaramla** [comment]
Hi @rajubhusani 

Yes, I have implemented this for both iOS and Android. Basically, this repository will be part of your web-based application which can act as a middleware between UAEPass and your Mobile Apps. Your mobile app can open a link (an address to your web-app which will redirect to UAEPass Auth Gateway) in the webview. On the app, you will have to monitor for webview's URL address change and once the address is same as your returned URL, you can log in a user to your app.
